# limited by py3-packaging version
FROM docker.io/amd64/alpine:3.12

RUN apk update && \
    apk add \
      autoconf automake bison build-base flex gettext libtool rsync texinfo \
      ca-certificates curl file gawk grep libarchive-tools py3-packaging python3 zstd
